# Mathematics, Linear Algebra, and Statistics

# NumPy: Mathematics Exercises

#### 41. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.

In [5]:
import numpy as np

arr = np.array([3, -5, 0, 8, -2])

sign_arr = np.sign(arr)

print("Original Array: ", arr)
print("Sign Array: ", sign_arr)

Original Array:  [ 3 -5  0  8 -2]
Sign Array:  [ 1 -1  0  1 -1]


#### 40. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.

In [10]:
x = np.array([
    [1, 2],
    [3, 4]
])
y = np.array([
    [1, 2],
    [3, 4]
])
ans = x ** y
print(ans)

[[  1   4]
 [ 27 256]]


# NumPy Linear Algebra

#### 13. Write a NumPy program to create an inner product of two arrays.

In [21]:
import numpy as np

x = np.arange(24).reshape((2, 3, 4))
print(x)
print('-'*40)
y = np.arange(4)
print(y)

print(np.inner(x, y))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------------------------------------
[0 1 2 3]
[[ 14  38  62]
 [ 86 110 134]]


#### 14. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

In [26]:
import numpy as np

x = np.array([1., 4., 0.])
y = np.array([2., 2., 1.])

print(x)
print(y)
print('-'*40)
print(np.inner(x, y))
print('-'*40)
print(np.outer(x, y))
print('-'*40)
print(np.cross(x, y))


[1. 4. 0.]
[2. 2. 1.]
----------------------------------------
10.0
----------------------------------------
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
----------------------------------------
[ 4. -1. -6.]


# NumPy: Statistics

#### 14. Write a NumPy program to compute the histogram of nums against the bins.

In [30]:
import numpy as np

nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])

hist, bin_edges = np.histogram(nums, bins)

print("nums:", nums)
print("bins:", bins)
print("Result:", (hist, bin_edges))


nums: [0.5 0.7 1.  1.2 1.3 2.1]
bins: [0 1 2 3]
Result: (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))


#### 13. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

In [35]:
import numpy as np

arr = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7, 15])

occurrences = np.bincount(arr)

print("Original array:")
print(arr)
print("Number of occurrences of each value in array:")
print(occurrences)


Original array:
[ 0  1  6  1  4  1  2  2  7 15]
Number of occurrences of each value in array:
[1 3 2 0 1 0 1 1 0 0 0 0 0 0 0 1]
