# Sorting, Searching, and Indexing

# Sorting and Searching

#### 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [20]:
import numpy as np
arr = np.array(
    [[10, 40],
    [30, 20]]
)
print(f"Original array: \n{arr}")
sorted_array_along_first_axis = np.sort(arr, axis = 0)
print(f"array sorted across first axis: \n{sorted_array_along_first_axis}")
sorted_array_along_last_axis = np.sort(arr, axis = 1)
print(f"array sorted across last axis: \n{sorted_array_along_last_axis}")

# flat_array = np.flatten(arr) this gives error, as there is no flatten method in np, but in the instance of array() itself
flat_array = arr.flatten()
# to flatten an array, there are other methods, also which can be used, like arr.ravel(), arr.reshape(-1)
# but the catch is that these methods sometimes modifies the original array, on the otherside, arr.flatten() dont
print(f"flattened array: \n{flat_array}")
sorted_flat_array = np.sort(flat_array)
print(f"sorted flat aray: \n{sorted_flat_array}")

Original array: 
[[10 40]
 [30 20]]
array sorted across first axis: 
[[10 20]
 [30 40]]
array sorted across last axis: 
[[10 40]
 [20 30]]
flattened array: 
[10 40 30 20]
sorted flat aray: 
[10 20 30 40]


#### 8. Write a  NumPy program to sort the specified number of elements from beginning of a given array.

In [24]:
import numpy as np

arr = np.array([0.39536213, 0.11779404, 0.32612381, 0.16327394, 0.98837963, 
                0.25510787, 0.01398678, 0.15188239, 0.12057667, 0.67278699])

n = 5

sorted_arr = np.copy(arr)
sorted_arr[:n] = np.sort(sorted_arr[:n])

print("Original array:")
print(arr)
print("\nSorted first 5 elements:")
print(sorted_arr)


Original array:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787
 0.01398678 0.15188239 0.12057667 0.67278699]

Sorted first 5 elements:
[0.11779404 0.16327394 0.32612381 0.39536213 0.98837963 0.25510787
 0.01398678 0.15188239 0.12057667 0.67278699]


#### 9. Write a NumPy program to sort an given array by the nth column.

In [34]:
import numpy as np

arr = np.array([[1, 5, 0],
                [3, 2, 5],
                [8, 7, 6]])

n = int(input(f"Enter value between 0 and {len(arr[0]) - 1}"))

sorted_arr = arr[arr[:, n].argsort()]

print("Original array:")
print(arr)

print("\nSorted by the nth column:")
print(sorted_arr)

Enter value between 0 and 2 1


Original array:
[[1 5 0]
 [3 2 5]
 [8 7 6]]

Sorted by the nth column:
[[3 2 5]
 [1 5 0]
 [8 7 6]]


# NumPy Advanced Indexing: Exercises, Practice, and Solutions

#### 20. Write a NumPy program that creates a 2D NumPy array and uses a mask array (boolean array) for indexing to select a subset of elements that match the mask criteria.

In [48]:
import numpy as np
arr = np.random.randint(0, 50, size=(5, 5))
print(f"original array: \n{arr}")
condition = arr > 25
print(f"Conditioned array: \n{condition}")
mask = arr[condition]
print(f"Masked array: \n{mask}")

original array: 
[[21  7  1  1 47]
 [ 2 46 26 32 30]
 [34 24  8 31 43]
 [23 18 16 13 34]
 [11  0 38 11 32]]
Conditioned array: 
[[False False False False  True]
 [False  True  True  True  True]
 [ True False False  True  True]
 [False False False False  True]
 [False False  True False  True]]
Masked array: 
[47 46 26 32 30 34 31 43 34 38 32]


#### 16. Write a NumPy program that creates a 2D NumPy array and uses np.nonzero to find indices of elements that satisfy a condition, then uses these indices for advanced indexing.

In [61]:
import numpy as np
arr = np.random.randint(0, 5, size = (5, 5))
print(f"Original array: \n{arr}", end = '\n'+ "-"*40 + "\n")
condition = arr < 3 # this is the conditon, this creates mask array, of the boolean values as per the condition
print(f"Conditioned array: \n{condition}", end = '\n'+ "-"*40 + "\n")
indices = np.nonzero(condition) # this method returns the indices of the array according to the conditons specified
print(f"Indices od array: \n{indices}", end = '\n'+ "-"*40 + "\n")
subset = arr[indices] # this gives the subset of the array, based on the tuple provided
# The return type is tuple containing arrays, and the arrays inside the tuple are of type numpy.ndarray.
print(f"Subset of array: \n{subset}", end = '\n'+ "-"*40 + "\n")

Original array: 
[[3 2 1 0 2]
 [4 3 0 0 2]
 [3 2 3 3 3]
 [3 0 1 0 2]
 [4 3 2 1 3]]
----------------------------------------
Conditioned array: 
[[False  True  True  True  True]
 [False False  True  True  True]
 [False  True False False False]
 [False  True  True  True  True]
 [False False  True  True False]]
----------------------------------------
Indices od array: 
(array([0, 0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4], dtype=int64), array([1, 2, 3, 4, 2, 3, 4, 1, 1, 2, 3, 4, 2, 3], dtype=int64))
----------------------------------------
Subset of array: 
[2 1 0 2 0 0 2 2 0 1 0 2 2 1]
----------------------------------------


#### 14. Write a NumPy program that creates a 2D NumPy array and uses slicing in combination with index arrays to select a rectangular subarray.

In [64]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

row_indices = np.array([0, 1, 2])  # Select rows 0, 1, 2
col_indices = np.array([1, 2])     # Select columns 1 and 2

subarray = arr[row_indices[:, None], col_indices]

print("Original array:")
print(arr)

print("\nSelected rectangular subarray:")
print(subarray)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Selected rectangular subarray:
[[ 2  3]
 [ 6  7]
 [10 11]]


#### Just leaning

In [69]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

diag_matrix = np.zeros_like(arr)  # Create a zero matrix of the same shape as arr
row_indices = np.arange(arr.shape[0])
col_indices = np.arange(arr.shape[1])
print(row_indices)
print(col_indices)
diag_matrix[np.arange(arr.shape[0]), np.arange(arr.shape[1])] = arr.diagonal()
ans = arr[row_indices[:, None], col_indices[:, None]]
ans1 = arr[[0, 1, 2], [0, 1, 2]]
print(diag_matrix)
print(ans)
print(ans1)


[0 1 2]
[0 1 2]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1]
 [5]
 [9]]
[1 5 9]


In [1]:
import numpy as np
arr = np.array([1, 2, 3])

print(arr[:, np.newaxis])  # Column vector
print(arr[np.newaxis, :])  # Row vector
print()
print('-'*40)
print(arr[:, None])
print(arr[None , : ])

print('-'*40)
row_indices = np.array([0, 1, 2])
col_indices = [0, 1, 2]
print(row_indices[:, None])

# print(np.array(col_indices[None:,]))  this wont work
col_indices = np.array(col_indices)
col_indices = np.array([0, 1, 2])
print(col_indices[None, :])
# print(arr[row_indices[:, None]])
# print(arr[row_indices[:, None]])

[[1]
 [2]
 [3]]
[[1 2 3]]

----------------------------------------
[[1]
 [2]
 [3]]
[[1 2 3]]
----------------------------------------
[[0]
 [1]
 [2]]
[[0 1 2]]
