# Sorting, Searching, and Indexing

# Sorting and Searching

#### 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [20]:
import numpy as np
arr = np.array(
    [[10, 40],
    [30, 20]]
)
print(f"Original array: \n{arr}")
sorted_array_along_first_axis = np.sort(arr, axis = 0)
print(f"array sorted across first axis: \n{sorted_array_along_first_axis}")
sorted_array_along_last_axis = np.sort(arr, axis = 1)
print(f"array sorted across last axis: \n{sorted_array_along_last_axis}")

# flat_array = np.flatten(arr) this gives error, as there is no flatten method in np, but in the instance of array() itself
flat_array = arr.flatten()
# to flatten an array, there are other methods, also which can be used, like arr.ravel(), arr.reshape(-1)
# but the catch is that these methods sometimes modifies the original array, on the otherside, arr.flatten() dont
print(f"flattened array: \n{flat_array}")
sorted_flat_array = np.sort(flat_array)
print(f"sorted flat aray: \n{sorted_flat_array}")

Original array: 
[[10 40]
 [30 20]]
array sorted across first axis: 
[[10 20]
 [30 40]]
array sorted across last axis: 
[[10 40]
 [20 30]]
flattened array: 
[10 40 30 20]
sorted flat aray: 
[10 20 30 40]
