# NumPy Performance Optimization

#### 20. Write a NumPy program that creates a large NumPy array and write a function to reverse its elements using a for loop. Optimize it using NumPy's slicing operations

In [59]:
import numpy as np
import time
def solution1(arr):
    a = 0
    n = len(arr) - 1
    arr = arr.copy()
    # swapping was not happening correctly in the previous case as the, numpy arrays do not allow python style swapping
    for i in range(len(arr) // 2):
        arr[i], arr[n - i] = arr[n - i],  arr[i]
    return arr
def solution2(arr):
    ans = arr[::-1]
    return ans

arr = np.array(np.random.randint(0, 100, 200000))


# print(f"Original array: \n{arr}")


start = time.perf_counter()
# print(f"Solution1: array: \n{solution1(arr)}")
solution1(arr)
end = time.perf_counter()
print(f"Time Taken: {(end - start)}")
print("-"*40)

start = time.perf_counter()
# print(f"Solution2: array: \n{solution2(arr)}")
solution2(arr)
end = time.perf_counter()
print(f"Time Taken: {(end - start)}")
print("-"*40)
# print(fun(arr))

Time Taken: 0.18132940004579723
----------------------------------------
Time Taken: 0.00012890005018562078
----------------------------------------


# NumPy Interoperability 

#### 20. Write a NumPy program to append a NumPy array to a Python list and print the result.

In [63]:
import numpy as np

py_list = [10, 20, 30]
np_array = np.array([40, 50, 60])

py_list.extend(np_array)

print("Updated Python List:", py_list)


Updated Python List: [10, 20, 30, 40, 50, 60]


# Input/Output (I/O) Operations

#### 20. Write a NumPy program to append a NumPy array to a Python list and print the result.

In [68]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

file_name = 'array_data.csv'

np.savetxt(file_name, data, delimiter=';', fmt='%d')

loaded_data = np.loadtxt(file_name, delimiter=';')

print('Loaded data:\n', loaded_data)


Loaded data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
