# NumPy Universal Functions

#### 20. Write a NumPy program that uses np.maximum.reduce to find the maximum element along a specified axis of a 2D array.

In [5]:
import numpy as np

arr = np.array([[1, 5, 3],
                [7, 2, 8],
                [4, 6, 9]])

max_along_axis0 = np.maximum.reduce(arr, axis=0)
max_along_axis1 = np.maximum.reduce(arr, axis=1)

print("Original array:")
print(arr)
print("\nMaximum along rows (axis 0):", max_along_axis0)
print("Maximum along columns (axis 1):", max_along_axis1)


Original array:
[[1 5 3]
 [7 2 8]
 [4 6 9]]

Maximum along rows (axis 0): [7 6 9]
Maximum along columns (axis 1): [5 8 9]


#### 19. Write a NumPy program that uses np.logical_and to combine two boolean arrays based on element-wise logical AND operation.

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([8, 1, 5, 4, 6])

result = np.logical_and(arr1 > 3, arr2 < 5)

print("mask 1:", arr1 > 3)
print("mask 2:", arr2 < 5)
print("Result of logical AND operation:", result)


mask 1: [False False False  True  True]
mask 2: [False  True False  True False]
Result of logical AND operation: [False False False  True False]


# Functions Masked Arrays

#### 20. Write a NumPy program that creates a masked array and checks if any masked elements are present.

In [16]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6])
masked_data = np.ma.masked_values(data, 3)

print("Masked Array:", masked_data)

if masked_data.mask.any():
    print("There are masked elements in the array.")
else:
    print("There are no masked elements in the array.")


Masked Array: [1 2 -- 4 5 6]
There are masked elements in the array.


#### 18. Write a NumPy program that creates a masked array and changes the mask to include additional elements.

In [35]:
import numpy as np
import numpy.ma as ma

arr = np.array(np.random.randint(0, 100, (5, 5)))
print(arr)

condition1 = arr < 35
masked_array = ma.masked_array(arr, condition1)
print(masked_array)
consition2 = arr > 90
masked_array.mask = masked_array.mask | consition2
print(masked_array)

[[39 15 38 56  8]
 [61 44  0 91 26]
 [25 50 97 72 18]
 [87 76 84 16 74]
 [26 24 24 51 39]]
[[39 -- 38 56 --]
 [61 44 -- 91 --]
 [-- 50 97 72 --]
 [87 76 84 -- 74]
 [-- -- -- 51 39]]
[[39 -- 38 56 --]
 [61 44 -- -- --]
 [-- 50 -- 72 --]
 [87 76 84 -- 74]
 [-- -- -- 51 39]]
